---
kind: pipeline
name: workspace

workspace:
  path: /drone/src

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    settings:
      repo:
        from_secret: workspace_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: ./Dockerfile
      tags:
        - latest
        - ${DRONE_TAG}
    when:
      branch:
        - master
trigger:
  event:
    - tag
