---
kind: pipeline
name: workspace

workspace:
  path: /drone/src

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    settings:
      repo:
        from_secret: workspace_repo
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: ./Dockerfile
    when:
      branch:
        - master
